### ISSUE TITLE
Quirking needs longer cooldown

### ISSUE THREAD

**Issue by jacklinzoho** [hadorganization/geheimnisnacht#26]
Druchii rulers get constantly quirked by Atharti courtiers.  Every time this happens you lose stats / gain negative traits or lose piety and prestige.  

opinion_recently_quirked in wh_cult_of_pleasure_events.txt is too short at 1 year; also if you have a large court you could get dogpiled even with it set high.  What we need is a recently_quirked flag that disallows quirking for say 10 years; also penalty for refusal should be reduced.

I'm pretty new at modding and am not sure how to set the flags properly here.

**Comment by hadaev8** [comment]
Mm, i will reduce the frequency of use of the decisions by AI.
