### ISSUE TITLE
casters should be allowed to cast some spells outside of combat

### ISSUE THREAD

**Issue by jacklinzoho** [hadorganization/geheimnisnacht#27]
Some spells have effect outside of combat, e.g. movement buff (shadow), summons (necromancy, beast lv3), create money (lore of metal).  Not a good idea to require the commander to be in combat for all of them.

ai = no in wh_magic_decisions only fixes this for the player, not the player's spellcaster commanders.

**Comment by hadaev8** [comment]
This is a temporary solution to the fact that the AI is spamming this decision, in the future will be a more detailed trigger or change magic.
I now put my attention on fixing the old events. Magic for the most part done well.
