### ISSUE TITLE
AIs stop using grail questing

### ISSUE THREAD

**Issue by smartwdf** [hadorganization/geheimnisnacht#37]
When I switched to the "bretonnia knight" character who stop doing grail quest, there is a decision "go to patrol" above "grail questing" decision. When I click "grail questing" decision nothing happens, instead "go to patrol" decision sent him to grail quest. I guess AIs are stucked by "grail questing decision".

**Comment by hadaev8** [comment]
May be fixed.

**Comment by smartwdf** [comment]
Sadly, as tested, nope. 
Tested as repanse de lyonesse for 10 game years, the "patrol your land" decision is still there. 
"Go on the Grail Quest" decision seems working now, however as I sent my character to Grail quest, no grail knight events triggered. Which means My character is on knight quest for 10 years and not a single event triggered thus unable to become a grail knight, During the 10 years there is alsp no other AI bretonnia knights become a grail knight, including bretonnia dukes and kings .
The character start the game as a grail knight, will occasionally have the trait "on Knight Quest", I guess it's due to bugged decision potential/trigger.

**Comment by hadaev8** [comment]
May be you not satisfy the trigger?

	only_playable = yes
	religion = grail
	min_age = 16
	only_men = yes
	prisoner = no

**Comment by smartwdf** [comment]
No, but it is supposed to work for Repanse de Lyonesse because she is a legendary lord!

**Comment by hadaev8** [comment]
A woman knight? What a nonsense?
But ok, fixed.

**Comment by smartwdf** [comment]
She is not only a woman knight but favoured by the lady of late, she was the one defeated an united norscan invasion. And she is an Legendary Lord.
