### ISSUE TITLE
New courtiers are spawning without race traits

### ISSUE THREAD

**Issue by jacklinzoho** [hadorganization/geheimnisnacht#44]
Traits like 'human', 'dwarf', etc are not happening.  Confirmed on latest master branch.

Step to reproduce: 1. start game as Von Carstein.  2. give away a castle.  3. wait a month for courtier spawn, then look in the court of the new lord.

**Comment by hadaev8** [comment]
Wait another month.
Also if you know what event spawn that characters (you can try to catch it by -debugscripts startup parameter in game.log) , we can add trait check into it.

**Comment by jacklinzoho** [comment]
Ah, I see what's going on.  It works on new games, but my savegame is stuffed.  Guess that's what happens when I try to use the same save after update.  Among other things, the Everqueen is now Burnt By Asuryan, and Malekith is now Everchild.
