### ISSUE TITLE
Imperial Reconquest

### ISSUE THREAD

**Issue by Gideones** [hadorganization/geheimnisnacht#71]
Imperial Claimants doesn't have casus belli "imperial reconquest". It's bug or feature?

**Comment by hadaev8** [comment]
Yes, it was bug, in the code condition by e_the_empire title (Empire).
In the normal mode it is available because error in the code that was fixed in one of updates.

I think that this war lasted a long time, and with this cb and current mechanics of ck2 it won't last so long.

So, it is more feature then bug.
But maybe it's part of the balance and it makes sense to change the condition to any imperial tier title.

**Comment by Gideones** [comment]
Thanks for answer. I think about "several" other things:
"Malekith" trait conflicts (-200) with "Black Guard" trait.
And one of trade houses of Remas haven't propriet icon and name (and two houses in Westerland rupublics too).
Sorry for my Engrish. My native language is Russian.

And, about balance, i have many things in each party (i think, it's bad things, but it's my point of view): Pigbarter republic falls every time, just like Shadowlands, pirat kingdoms in Amazonia, Skeggi and Colony of Santa Magritta. 

And many houses with unique names and icons falls after 5 years of game because they haven't heirs -
 it's republics of Tilea, Estalia, Boghenhafen, all of them, and in Westerland republics it's houses van Daalen and Breedlveld;
Three Kingdoms in Tilea and Estalia (Houses Gomez, di Miragliano, and house di Castalnasseta), one county in Remas (house Bonetti);
Houses of Arabia (Abergel, Almasi, Maqdisi, Shawkat, Kalbid, Darbi), 
Houses of Bretonia (de Mostuejouls, de Beaujeu, de Poiotu (duke Markus often dies in battle with Red Duke), de Ville, du Dross, de Bessa, de Saint-Denis, d'Abzac); 
Houses of Kislev (Ulyanov, Raadelma, Kolga, Gostautas, Davidovich).

About graphic. Several character in non human races have wrong immortality (allways children, i mean) - it's Guttri of Karak Norn (53045), Tullaris in Dark Elfs (90500) and, i remember about Teclis and Tyrion, but i don't know about now.
And minor characters, like Lilrenisa (95212), Seladon (95240), Telulmil (95143), Rienir (95073), Cadorisa (95253), Kyrlath 95263, in Ulthuan.
Minor characters in Naggaroth: Valekith (90970), Gloraneth (90963), Sarophas (90916), Illidoth (90901), Telestra (90972).

About suggestions: nicknames for elven and vampiric characters characters with history? I think about:
Dark Elves: Morathi (90300) "the First of Hug Queens", Hellebron (90531) "the Blood Queen", Tullaris (90500) "Dreadbringer", Malus (90209) "Darkbalde", Kouran (90979) "Darkhand". 
High Elves: Alith (18061) "the Shadow King" (and, about Alith, he is a king of Nagarythe, but in game, he is a leader of mercenary company, i'm right?), Eltharion (95061) "the Grim", and nicknames for Teclis and Tyrion.
Vampires: Heloise (15010) "Madame", Heferata (15025) "the First of the Vampires', Zacharius (15009) "the Everliving), Ushoran (15000) "the King of Masques, Celebrations and Festivities", Red Duke (15018) "the Scourge of Aquitaine", Manfred (80008) "the Acolyte", Conrad (Konrad on warhammerwiki) (80005) "the Bloody".
Nehekhara: Khalida (11017) "the Warrior Queen", Sehenesmet (in game - Schenesmet) (11033) "the Vizier".
And empty nicknames for several characters, like Vlad von Carstain, Isabella von Drak. 
And i think about one histoical character in Naggaroth - it's Lokhir Fellheart (commander Tower of Blessed Dread in 2010). He isn't present in the game.

Sorry for wall of text. I like your submod and you make good think for fans of warhammer.

**Comment by hadaev8** [comment]
Лично я вряд ли скоро займусь персонажами, ты мог бы сам это исправить/улучшить, это не трудно.

Имперский реконквест подразумевает возврат территории настоящей империи.
Насколько я помню, по бэку империю делили 300 лет (обычные войны по клаймам и тд), но так и не поделил и собрались по эвенту, что в моде есть.

**Comment by Gideones** [comment]
Ок.
Что-то лениво мне, да и загрузка есть на учебе. Но, если будет свободное время и желание (что бывает чаще, чем хотелось бы), то, думаю, займусь этим. И так все поправил у себя в сейвах, думаю разберусь и с файлами. 
В общем, если что изменю и до этого не будет этих изменений в сабмоде - свяжусь.
По поводу реконквеста - да, делили, но в партиях у меня за сто лет никто даже не приблизился к сбору Империи. А вот постоянные гуляния герцогств неслабо оживляют процесс и создают ощущение "реальной" борьбы между претендентами. Но это мое мнение.
И еще раз спасибо тебе за ответ и благодарю за сабмод. Блага и удачи в моддинге и жизни.
