### ISSUE TITLE
Краши при срабатывании ивента

### ISSUE THREAD

**Issue by xanderb** [hadorganization/geheimnisnacht#72]
Игра постоянно вылетает при срабатывании одного и того же ивента. В game.log последней записью было это: 
[effectimplementation.cpp:18122]: EVENT [2029.4.16]:work event id = wh_chaos.1 for 
На форуме такая же проблема у еще одного человека, ошибка скорей всего не локальная: https://www.strategium.ru/forum/topic/82247-tehnicheskie-voprosy-i-reshenie-problem-moda-%C2%ABwarhammer-geheimnisnacht%C2%BB/?do=findComment&comment=2478053
Файл сейва: https://yadi.sk/d/RgHPeF543PBtU8

**Comment by hadaev8** [comment]
Попробуй сейчас.

**Comment by Brivelverp** [comment]
вылетает как повезёт , может через минут 10 , а может через час, сильно грузится hdd(фриз) и вылетает в логах error.txt пишет целые мемуары 
[error.log](https://github.com/hadorganization/geheimnisnacht/files/1443197/error.log)
(сохранение игры)https://drive.google.com/open?id=1CH6vkJOoN4wDmd3qWFQ24_vQyHrIlD1p

**Comment by hadaev8** [comment]
Я почистил чутка еррор лог, но он не поможет установить причину вылетов, которая может быть из-за багнутого эвента (тогда включать логирование и смотреть в гейм логе) или пк.

**Comment by Jarteks** [comment]
На форуме об этой проблеме писал я, как временное решения для себя я удалил из файла event\wh_chaos самую первую строчку отвечающую за ивент под номером 1, который крашит игру

**Comment by Jarteks** [comment]
Но увы пытаясь решить проблему с крашами я обновил мод ,а играть я все равно не могу, т.к. поломаны советники в последней сборке

**Comment by Brivelverp** [comment]
звучит как кастыль , но лучше так чем надеется что сможешь посидеть на пару минут больше без вылета

**Comment by hadaev8** [comment]
Краш должен быть исправлен, советники должны работать.
Без флуда плиз, каждая проблема в отдельной ветке.
