### ISSUE TITLE
Стабильный вылет 2041.5.4

### ISSUE THREAD

**Issue by FlashWarior** [hadorganization/geheimnisnacht#74]
[game.log](https://github.com/hadorganization/geheimnisnacht/files/1464116/game.log)

[сейв.zip](https://github.com/hadorganization/geheimnisnacht/files/1464119/default.zip)

**Comment by FlashWarior** [comment]
я щас перекачаю мод на всякий

**Comment by FlashWarior** [comment]
не помогло

**Comment by hadaev8** [comment]
Да, у меня тоже вылет, завтра попробую 1 вариант.

**Comment by FlashWarior** [comment]
последние обновы не спасли ситуацию

**Comment by hadaev8** [comment]
Низнаю, дело скорей всего не в эвентах.
Других идея нет.

**Comment by hadaev8** [comment]
Можно попробовать добавить в лог решения, может есть какое-то багнутое решение, которое юзает ии. Но дело может быть и не в решении.

**Comment by FlashWarior** [comment]
т.е. на пока могу забить на этот сейв?

**Comment by FlashWarior** [comment]
пойду в сторону лесных эльфов

**Comment by hadaev8** [comment]
Ну походу да, там в патче игры обещают пофиксить некоторые причины вылетов в модах, вдруг это оно.
